version: "3"

services:
  react-native:
    build: .
    container_name: react-native-workshop
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME
    volumes:
      - ./:/var/react-native-src
    ports:
      - 19000:19000
      - 19001:19001
      - 8081:8081
